### ISSUE TITLE
Preservica Resync batch processes not completing

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#2166]
**Story**

During Preservica working testing on #2138, test for resyncing sort order changes or deleted file changes are not completing in DCS. See these two batches 
https://collections-uat.library.yale.edu/management/batch_processes/1141/parent_objects/900148026 
https://collections-uat.library.yale.edu/management/batch_processes/1142/parent_objects/900145752

This might be the same issue we surfaced in #2105

**Acceptance**
- [x] When a file is deleted in Preservica for an existing parent in DCS, the resync with Preservica batch process successfully completes all steps in the process and removes that child from DCS
- [x] When a file is reordered in Preservica for an existing parent in DCS, the resync with Preservica batch process successfully completes all steps in the process and reorders that child from DCS

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1044

**Comment by motropuk** [comment]
Resync is completing successfully. Spotted and issue with reporting within the batch process, but will create a separate ticket for this

**Comment by motropuk** [comment]
Reopening this ticket. While these resyncs now work, there is an issue in that the batch process screen shows two parent processes, even though it is only resyncing one parent. @K8Sewell will investigate![Screen Shot 2022-08-10 at 14.21.02.png](https://images.zenhubusercontent.com/60786c408c8643227aa47d8f/e981c3a3-72da-4d11-96e1-72d9a0d163a2)

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1049

**Comment by mikeapp** [comment]
I merged this but a test failed: https://app.circleci.com/pipelines/github/yalelibrary/yul-dc-management/5693/workflows/37789ed4-321a-4fc1-8ffc-44f41026db40/jobs/11805
* Release is v2.59.56
* PR to back it out: https://github.com/yalelibrary/yul-dc-management/pull/1050

**Comment by motropuk** [comment]
Dual parent issue in the batch process is fixed, but the batch process is not completing again now. @K8Sewell will explore.

**Comment by K8Sewell** [comment]
PR Ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1060

Manually sets batch status that was not reporting.

**Comment by K8Sewell** [comment]
Release [v2.59.59](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.59) deployed to test

**Comment by motropuk** [comment]
Resync still not completing https://collections-uat.library.yale.edu/management/batch_processes/1163/parent_objects/900140256

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1064

**Comment by K8Sewell** [comment]
Release [v2.59.60](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.60) deployed to UAT

**Comment by motropuk** [comment]
Still no luck in UAT https://collections-uat.library.yale.edu/management/batch_processes/1168/parent_objects/900145624

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1069

**Comment by K8Sewell** [comment]
Release [v2.59.63](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.63) deployed to Test

**Comment by DraxIndustries79** [comment]
@motropuk for testing

**Comment by K8Sewell** [comment]
Failing on UAT so taking back to in progress to investigate - https://collections-uat.library.yale.edu/management/batch_processes/1188

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1072

Will give us a more specific error so we can see what really needs addressed.

**Comment by martinlovell** [comment]
In release v2.59.65

**Comment by motropuk** [comment]
Tested here https://collections-uat.library.yale.edu/management/batch_processes/1197

Got the following Error 

Parent OID: 900148026 because of Request error 500 <?xml version="1.0" encoding="UTF-8" standalone="yes"?><Error><ExtendedMessage>An unexpected error occurred. Please see server logs for details.</ExtendedMessage><MessageKey>unexpected.error</MessageKey></Error> for /structural-objects/492fd76f-5f4e-497e-bd17-5d73953745f1

**Comment by martinlovell** [comment]
I get the same error using the client and making a get request to: 
`/api/entity/structural-objects/492fd76f-5f4e-497e-bd17-5d73953745f1`
The call takes a while to return....maybe 5 seconds. 

It doesn't seem to be related to the ID.  I tried 1b98e010-3a3d-40b5-878b-3601e3de71c0 and just random UUIDs, and go the same error for all of them.

**Comment by motropuk** [comment]
DPS confirmed that the call error we are seeing is most likely caused by a set of bugs that started happening after upgrade to Preservica 6.5. They have not occurred on every call, but DPS has been working with Preservica and LIT make some changes that should improve things.

**Comment by DraxIndustries79** [comment]
Waiting to hear re: Preservica side

**Comment by motropuk** [comment]
DPS report that issues in Preservica TEST v6.5, that were causing the API call errors we were seeing, have now been fixed. API calls from DCS now appear to be working, and interestingly, this call which was previously not completing, is now completing https://collections-uat.library.yale.edu/management/batch_processes/1202. We are seeing two parents in the batch process report still, but the sync appears to be working

**Comment by martinlovell** [comment]
Great.  I think the duplicates in the report will be fixed in https://github.com/yalelibrary/yul-dc-management/pull/1074
